package com.github.playernguyen.inject;

/**
 * Interface that all generated injection providers must implement.
 * Providers are generated by the annotation processor for each component.
 */
public interface InjectionPoint {
    /**
     * Creates a new instance of the component, with dependencies injected.
     * 
     * @param container the injection container
     * @return a new instance of the component
     */
    Object provide(Object container);
}
