package com.github.playernguyen.runtime;

import com.github.playernguyen.inject.Component;
import com.github.playernguyen.inject.InjectionException;
import com.github.playernguyen.inject.InjectionPoint;
import io.github.classgraph.ClassGraph;
import io.github.classgraph.ClassInfo;
import io.github.classgraph.ScanResult;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Scans for and registers components with the injection container.
 * Uses ClassGraph for efficient and reliable classpath scanning.
 * 
 * Supports:
 * - Auto-scanning packages for @Component classes
 * - Manual registration of individual components
 * - Automatic provider discovery and loading
 */
public class ComponentScanner {

    private final InjectionContainer container;
    private final Set<String> scannedPackages = new HashSet<>();

    public ComponentScanner(InjectionContainer container) {
        this.container = container;
    }

    /**
     * Scans multiple packages for components and registers them.
     * 
     * @param packageNames the packages to scan
     */
    public void scanPackages(String... packageNames) {
        for (String packageName : packageNames) {
            scanPackage(packageName);
        }
    }

    /**
     * Scans the classpath for components and registers them.
     * Looks for classes in the same package as a reference class.
     * 
     * @param referenceClass a class in the package to scan
     */
    public void scanPackage(Class<?> referenceClass) {
        scanPackage(referenceClass.getPackageName());
    }

    /**
     * Scans a specific package for components and registers them.
     * Uses ClassGraph for efficient classpath scanning.
     * 
     * @param packageName the package to scan
     */
    public void scanPackage(String packageName) {
        if (scannedPackages.contains(packageName)) {
            return;  // Already scanned this package
        }

        try (ScanResult scanResult = new ClassGraph()
                .acceptPackages(packageName)
                .enableClassInfo()           // Enable class information
                .enableAnnotationInfo()      // Enable annotation scanning
                .scan()) {
            
            for (ClassInfo classInfo : scanResult.getClassesWithAnnotation(Component.class.getName())) {
                try {
                    Class<?> clazz = Class.forName(classInfo.getName());
                    registerComponent(clazz);
                } catch (ClassNotFoundException e) {
                    throw new InjectionException("Failed to load class: " + classInfo.getName(), e);
                }
            }
            
            scannedPackages.add(packageName);
        } catch (Exception e) {
            throw new InjectionException("Error scanning package: " + packageName, e);
        }
    }

    /**
     * Registers a single component class with the container.
     * Automatically discovers and loads the generated provider class.
     * Also registers the component by its interface types.
     * 
     * @param componentClass the component class to register
     */
    public void registerComponent(Class<?> componentClass) {
        Component componentAnnotation = componentClass.getAnnotation(Component.class);
        if (componentAnnotation == null) {
            throw new InjectionException("Class is not annotated with @Component: " + componentClass.getName());
        }

        String componentName = componentAnnotation.value();
        if (componentName.isEmpty()) {
            componentName = componentClass.getName();
        }

        // Load the generated provider
        InjectionPoint provider = loadProvider(componentClass);
        
        // Register by custom name or full class name
        container.register(componentName, provider);
        
        // Also register by interface types if component implements interfaces
        for (Class<?> iface : componentClass.getInterfaces()) {
            container.register(iface.getName(), provider);
        }
    }

    /**
     * Loads the generated provider class for a component.
     * The provider must have been generated by the annotation processor.
     * 
     * @param componentClass the component class
     * @return the instantiated provider
     */
    /**
     * Sub-package where the annotation processor emits generated provider classes.
     * Must stay in sync with {@code InjectionProcessor.GENERATED_SUBPACKAGE}.
     */
    private static final String GENERATED_SUBPACKAGE = "generated";

    private InjectionPoint loadProvider(Class<?> componentClass) {
        // Generated providers live in a dedicated "generated" sub-package to avoid
        // name collisions with any hand-written class whose name ends in "Provider".
        String providerClassName = componentClass.getPackageName() + "."
            + GENERATED_SUBPACKAGE + "."
            + componentClass.getSimpleName() + "Provider";
        
        try {
            Class<?> providerClass = Class.forName(providerClassName);
            return (InjectionPoint) providerClass.getDeclaredConstructor().newInstance();
        } catch (ClassNotFoundException e) {
            throw new InjectionException(
                "Generated provider not found. Make sure annotation processor ran.\n" +
                "Expected: " + providerClassName + "\n" +
                "Component: " + componentClass.getName(),
                e
            );
        } catch (InstantiationException | IllegalAccessException | InvocationTargetException | NoSuchMethodException e) {
            throw new InjectionException("Failed to instantiate provider: " + providerClassName, e);
        }
    }

    /**
     * Get list of scanned packages.
     * Useful for debugging.
     * 
     * @return set of package names that have been scanned
     */
    public Set<String> getScannedPackages() {
        return new HashSet<>(scannedPackages);
    }
}
